[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wordle-solver-strategy"
version = "0.1.0"
description = "A fast Wordle solver written in Python using numba."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "numba",
  "pandas",
  "scipy",
  "scikit-learn",
  "requests",
]

[project.scripts]
wordle-demo-solver = "wordle_solver_strategy.demos.demo_solver:main"
wordle-demo-game = "wordle_solver_strategy.demos.demo_game:main"
wordle-demo-ig = "wordle_solver_strategy.demos.demo_ig:main"
wordle-bs-plays = "wordle_solver_strategy.demos.bs_plays:main"
wordle-bs-tiles = "wordle_solver_strategy.demos.bs_tiles:main"
wordle-ngram-download = "wordle_solver_strategy.demos.ngram_download:main"
wordle-exp-comparison-standard = "wordle_solver_strategy.experiments.comparison_standardmode:main"
wordle-exp-comparison-hard = "wordle_solver_strategy.experiments.comparison_hardmode:main"
wordle-exp-first-guess-standard = "wordle_solver_strategy.experiments.first_guess_standard:main"
wordle-exp-first-guess-hard = "wordle_solver_strategy.experiments.first_guess_hardmode:main"
wordle-exp-first-guess-shallow = "wordle_solver_strategy.experiments.first_guess_shallow:main"
wordle-exp-cross-validate = "wordle_solver_strategy.experiments.cross_validate:main"

[tool.setuptools.packages.find]
where = ["src"]
